---title: "Class Exercise (Group 7)"author: "Team Members: Simeng Zeng, Robert Curtis, Scott Haviland, Takashi Takizawa"date: "Mar 14, 2017"output:  html_document:     toc: yes    toc_float: yes---```{r setup, include=FALSE}knitr::opts_chunk$set(echo = TRUE)```###Set up: Import the data```{r}suppressPackageStartupMessages(library(nycflights13))nyc <- nycflights13::flights```###Airport ComparationComparasion of average delay for the three NYC airports: JFK has the average lowest arrival delay by the barchart below.```{r}arr_delay.overall=tapply(nyc$arr_delay,nyc$origin,mean,na.rm=TRUE)barplot(arr_delay.overall,main="Average Arrival Delay for NYC Airports", xlab="Ariport",ylab = "average arrvial delay(min)")```###Airport Comparision by MonthsFurthermore, let's compare the average arrival delay by month.```{r}nyc.ewr=subset(nyc,nyc$origin=="EWR")nyc.jfk=subset(nyc,nyc$origin=="JFK")nyc.lga=subset(nyc,nyc$origin=="LGA")nyc.ewr.month=tapply(nyc.ewr$arr_delay,nyc.ewr$month,mean,na.rm=TRUE)nyc.jfk.month=tapply(nyc.jfk$arr_delay,nyc.jfk$month,mean,na.rm=TRUE)nyc.lga.month=tapply(nyc.lga$arr_delay,nyc.lga$month,mean,na.rm=TRUE)nyc.month=rbind(nyc.ewr.month,nyc.jfk.month,nyc.lga.month)barplot(nyc.month,beside=T, legend.text = T,main="Average Arrival Delay by Month for NYC Airports",xlab="Month",ylab = "monthly average arrival delay(min)")```More specifically, we can obtain the comparision in a given month, say, May```{r}barplot(nyc.month[,5],names.arg = c("EWR","JFK","LGA"),main="Average Arrival Delay in May for NYC Airports",xlab="Ariport",ylab = "Average Arrival Delay(min)")```###Impact of DestinationIn this part, we examine whether destinations affect the arrival delay by using the case of Atlanta.```{r}nyc.ewr.atl=subset(nyc.ewr,nyc.ewr$dest=="ATL")nyc.jfk.atl=subset(nyc.jfk,nyc.jfk$dest=="ATL")nyc.lga.atl=subset(nyc.lga,nyc.lga$dest=="ATL")nyc.ewr.atl.month=tapply(nyc.ewr.atl$arr_delay,nyc.ewr.atl$month,mean,na.rm=TRUE)nyc.jfk.atl.month=tapply(nyc.jfk.atl$arr_delay,nyc.jfk.atl$month,mean,na.rm=TRUE)nyc.lga.atl.month=tapply(nyc.lga.atl$arr_delay,nyc.lga.atl$month,mean,na.rm=TRUE)nyc.month.atl=rbind(nyc.ewr.atl.month,nyc.jfk.atl.month,nyc.lga.atl.month)barplot(nyc.month.atl,beside=T, legend.text = T,main="Average Arrival Delay by Month towards Atlanta for NYC Airports",xlab="Month",ylab = "monthly average arrival delay to Atlanta(min)")```###Time of FlightIn this part, we aim to exmaine whether different time of flight can cause different delay time. The barchart below shows that a heavy arrival delay is more likely to happen in the evening (18:01pm-4:00am) rather than morning (4:01am-12:00pm) and afternoon (12:01pm-18:00pm)```{r}TimeSeg=function(x){  if (is.na(x)==TRUE){    Time=NA  } else if (x>=401 & x<=1200){    Time="Morning"  } else if (x>=1201 & x<=1800){    Time="Afternoon"  } else {    Time="Evening"  }  Time}nyc$Time=sapply(nyc$dep_time,FUN=TimeSeg)time.period=tapply(nyc$arr_delay,nyc$Time,mean,na.rm=TRUE)barplot(time.period,main="Average Arrival Delay Sorted by Time Period for NYC Airports", xlab="Time Period",ylab = "average arrvial delay(min)")```